org: minirobotdan
app: python-athena
service: python-athena

provider:
    region: eu-west-1
    name: aws
    runtime: python3.7

functions:
    hello:
        handler: handler.endpoint
        events:
        - http:
            path: hello
            method: get
plugins:
  - serverless-python-requirements
